spring:
  application:
    name: edu-tracker-student
  datasource:
    url: jdbc:mysql://localhost:3306/edutracker
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: localhost
    port: 7653
    username: root
    password: 1234
server:
  servlet:
    context-path: /edu-tracker/student/
  host: localhost
  port: 8082
minio:
  accessKey: admin
  secretKey: password
  endpoint: http://localhost:7651