spring:
  application:
    name: edu-tracker-student
  datasource:
    url: jdbc:mysql://localhost:3306/edutracker
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /edu-tracker/student/
  port: 8082

minio:
  accessKey: admin
  secretKey: password
  endpoint: http://slj.demodev.cc:4401