spring:
  application:
    name: edu-tracker-student
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: slj-edutracker-rabbit
    port: 5672
    username: root
    password: 1234
server:
  servlet:
    context-path: /edu-tracker/student/
  host: slj.demodev.cc
  port: 7657
minio:
  accessKey: admin
  secretKey: password
  endpoint: http://minio:9000